### ISSUE TITLE
No frames generated + catch-22 behaviour

### ISSUE THREAD

**Issue by liorgolgher** [HagaiHargil/python-pysight#1]
Ahlan,

1. The following file seemingly contains 4 frames, based on visual inspection. 2904 lines were resolved but a single frame was generated:
/data/Lior/Multiscaler data/TAG lens in FITC dish/masking tape edge-1024x1024 - 2x zoom - TAG OFF - 002.lst

2. The following files were taken with TAG lens off in START channel, and possibly with a deactivated START channel:
/data/Lior/Multiscaler data/TAG lens in FITC dish/masking tape edge-1024x1024 - 2x zoom - TAG OFF - 003.lst
/data/Lior/Multiscaler data/TAG lens in FITC dish/masking tape edge-1024x1024 - 2x zoom - TAG OFF - 004.lst

When processed with empty START channel it fails with the following warning:

UserWarning: Channels that were inserted in GUI don't match actual data channels recorded. 
Recorded channels are {'010', '001', '110'}.

When processed with TAG lens at START channel it fails with following warning:

UserWarning: Wrong number of user inputs (3) compared to number of actual inputs (2).

Should it work some other way?

Thanks,
Lior

**Comment by HagaiHargil** [comment]
Regarding #2, the file is corrupt.
First, the list file reports of data lost bits, which we know make the multiscaler go mad.
Second, the multiscaler reported 2 active channels when it created the list files (hence the second warning), but since the file contains inputs from 3 channels (=corrupted) the code fails. Sadly, there isn't really anything I can do about it. Garbage in, garbage out.

I will now turn to deal with issue #1.

**Comment by HagaiHargil** [comment]
I found a bug in the image segmentation algorithm and fixed it.
As we said, the file contains data lost bits, so I wouldn't rely on its output. 

I will add support for 3-pulses-per-period TAG signal.
